on:
  workflow_dispatch:
  push:
    tags:        
      - '**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  export_linux:
    name: Export (Linux)
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: Install Godot
      run: |
        curl -o godot https://github.com/Draconizations/godot-petz/releases/download/v0.1.0/godot_server.x11.opt.tools.64
        chmod +x godot

    - name: Install Export Template
      run: |
        mkdir export && cd export
        curl -o godot.x11.opt.64 https://github.com/Draconizations/godot-petz/releases/download/v0.1.0/godot.x11.opt.64
        cd ..
        ls

    - name: Export LnzLive
      run: ./godot --export "linux" /var/builds/LnzLive-linux_${{ github.ref_name || 'nightly' }}.x11.64

    - uses: actions/upload-artifact@v7
      with:
        name: LnzLive-linux_${{ github.ref_name || 'nightly' }}.x11.64
        path: /var/builds/LnzLive-linux_${{ github.ref_name || 'nightly' }}.x11.64

  export_windows:
    name: Export (Windows)
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: Install Godot
      run: |
        curl -o godot https://github.com/Draconizations/godot-petz/releases/download/v0.1.0/godot_server.x11.opt.tools.64
        chmod +x godot

    - name: Install Export Template
      run: |
        mkdir export && cd export
        curl -o godot.windows.opt.64.exe https://github.com/Draconizations/godot-petz/releases/download/v0.1.0/godot.windows.opt.64.exe
        cd ..

    - name: Export LnzLive
      run: ./godot --export "windows" /var/builds/LnzLive-windows_${{ github.ref_name || 'nightly' }}.exe

    - uses: actions/upload-artifact@v7
      with:
        name: LnzLive-windows_${{ github.ref_name || 'nightly' }}.exe
        path: /var/builds/LnzLive-windows_${{ github.ref_name || 'nightly' }}exe

  export_web:
    name: Export (Web)
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: Install Godot
      run: |
        curl -o godot https://github.com/Draconizations/godot-petz/releases/download/v0.1.0/godot_server.x11.opt.tools.64
        chmod +x godot

    - name: Install Export Template
      run: |
        mkdir export && cd export
        curl -o javascript-template.zip https://github.com/Draconizations/godot-petz/releases/download/v0.1.0/javascript-template.zip
        cd ..

    - name: Export LnzLive
      run: ./godot --export "windows" /var/builds/LnzLive-web_${{ github.ref_name || 'nightly' }}.zip

    - uses: actions/upload-artifact@v7
      with:
        name: LnzLive-web_${{ github.ref_name || 'nightly' }}.zip
        path: /var/builds/LnzLive-web_${{ github.ref_name || 'nightly' }}.zip